id: P1A43637D
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1KG5809
  instance_id: http://purl.bdrc.io/resource/IE1KG5809
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - རྗེ་བྱ་བཏང་བ་སངས་རྒྱས་རྡོ་རྗེ་དཔལ་བཟང་པོའི་རྣམ་ཐར་སྒྲུབ་བརྒྱུད་བསྟན་པའི་མཛེས་རྒྱན་ཛམྦུ་ཆུ་བོའི་གསེར་གྱི་ཕྲེང་བ།
  alt_title: {}
  author: http://purl.bdrc.io/resource/P1KG5810
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    973aca3d87fe489496bc6e2f16bb2f2b:
      title: པོད ༡་རྗེ་བྱ་བཏང་བ་སངས་རྒྱས་རྡོ་རྗེ་དཔལ་བཟང་པོའི་རྣམ་ཐར་སྒྲུབ་བརྒྱུད་བསྟན་པའི་མཛེས་རྒྱན་ཛམྦུ་ཆུ་བོའི་གསེར་གྱི་ཕྲེང་བ
      volume_number: 1
      base_file: UT1KG5809_I1KG5826_0000.txt
      reference: http://purl.bdrc.io/resource/VL30D7123F783F38E4
      image_group: I1KG5826
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/W1KG5809
  - http://purl.bdrc.io/resource/MW1KG5809
  ocr_software: Namsel
created_at: '2021-12-22T10:52:48.479850'
last_modified_at: '2021-12-22T10:52:48.479857'
statistics:
  total_words: 21903
  total_non_words: 2582
quality:
  non_words_ratio: 0.12
